EMC=emc
ENV=test_env
BIN=event_handlers event_handler_parameters disc_node_list

all: clean $(BIN)

%:%.m
	@(echo "load $(ENV)" && echo $^) | $(EMC)

clean:
	rm -f *.x *.oid *.idb *.opd *.ats *.oid $(ENV)
